apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.namespace }}
  labels:
    notebook-name: {{ .Chart.Name }}
spec:
  selector:
    matchLabels:
      notebook-name: {{ .Chart.Name }}
  replicas: 1
  template:
    metadata:
      labels:
        notebook-name: {{ .Chart.Name }}
        {{ if .Values.classification }}
        data.statcan.gc.ca/classification: {{ .Values.classification }}
        {{ end }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        {{ toYaml .Values.image | nindent 8 }}
        {{ if not .Values.image.env }}
        env:
        {{ end }}
        - name: NB_PREFIX
          value: /notebook/{{ .Values.namespace }}/{{ .Chart.Name }}
        ports:
        - containerPort: {{ .Values.targetPort }}
