apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.namespace }}
spec:
  ports: 
  - name: http-port
    port: 80
    targetPort: {{ .Values.targetPort }}
  selector:
    notebook-name: {{ .Chart.Name }}
