apiVersion: kubeflow.org/v1
kind: Notebook
metadata:
  name: jupyter
  namespace: alice
spec:
  template:
    spec:
      containers:
      - env:
        - name: KF_LANG
          value: en
        image: jupyter/minimal-notebook
        name: jupyter
        resources:
          limits:
            cpu: "1"
            memory: 4Gi
          requests:
            cpu: "1"
            memory: 4Gi
      serviceAccountName: default-editor
      volumes: []
