apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  namespace: alice #root namespace 
  name: jupyter-protected-b-block
spec:
  selector:
    matchLabels:
      data.statcan.gc.ca/classification: protected-b
  action: DENY
  rules:
  - to:
    - operation:
        methods: ["GET"]
        paths: ["/notebook/alice/jupyter/files*",]
        
