namespace: rstudio

# classification: unclassified
# classification: protected-b

image:
  image: blairdrummond/blair-rstudio
  imagePullPolicy: IfNotPresent
  command: ["jupyter"]
  args:
  - "notebook"
  - "--ip=0.0.0.0"
  - "--no-browser"
  - "--port=8888"
  - "--NotebookApp.token=''"
  - "--NotebookApp.password=''"
  - "--NotebookApp.allow_origin='*'"
  - "--NotebookApp.authenticate_prometheus=False"
  - "--NotebookApp.base_url=$(NB_PREFIX)"
  - "--NotebookApp.default_url=/rstudio"

targetPort: 8888

host: kubeflow.muchk8s.wow
