apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.namespace }}
spec:
  hosts:
  - {{ .Values.host }}
  gateways:
  - istio-system/ingressgateway
  http:
  - match:
    - uri:
        prefix: "/notebook/{{ .Values.namespace }}/{{ .Chart.Name }}"
    route:
    - destination:
        host: {{ .Chart.Name }}.{{ .Values.namespace }}.svc.cluster.local
